/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'organization' : IDL.Opt(IDL.Text),
});
export const ContactMessage = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const DonationPledge = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const VolunteerInterest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'availability' : IDL.Text,
  'message' : IDL.Text,
  'address' : IDL.Text,
  'contactNo' : IDL.Text,
  'areaOfInterest' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessageByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ContactMessage)],
      ['query'],
    ),
  'getDonationPledgeByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DonationPledge)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVolunteerInterestByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VolunteerInterest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listDonationPledges' : IDL.Func([], [IDL.Vec(DonationPledge)], ['query']),
  'listVolunteerInterests' : IDL.Func(
      [],
      [IDL.Vec(VolunteerInterest)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func([ContactMessage], [], []),
  'submitDonationPledge' : IDL.Func([DonationPledge], [], []),
  'submitVolunteerInterest' : IDL.Func([VolunteerInterest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'organization' : IDL.Opt(IDL.Text),
  });
  const ContactMessage = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const DonationPledge = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const VolunteerInterest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'availability' : IDL.Text,
    'message' : IDL.Text,
    'address' : IDL.Text,
    'contactNo' : IDL.Text,
    'areaOfInterest' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessageByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContactMessage)],
        ['query'],
      ),
    'getDonationPledgeByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DonationPledge)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVolunteerInterestByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VolunteerInterest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listDonationPledges' : IDL.Func([], [IDL.Vec(DonationPledge)], ['query']),
    'listVolunteerInterests' : IDL.Func(
        [],
        [IDL.Vec(VolunteerInterest)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func([ContactMessage], [], []),
    'submitDonationPledge' : IDL.Func([DonationPledge], [], []),
    'submitVolunteerInterest' : IDL.Func([VolunteerInterest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };