/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface DonationPledge {
  'name' : string,
  'email' : string,
  'message' : [] | [string],
  'amount' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'organization' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VolunteerInterest {
  'name' : string,
  'email' : string,
  'availability' : string,
  'message' : string,
  'areaOfInterest' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessageByEmail' : ActorMethod<[string], [] | [ContactMessage]>,
  'getDonationPledgeByEmail' : ActorMethod<[string], [] | [DonationPledge]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVolunteerInterestByEmail' : ActorMethod<
    [string],
    [] | [VolunteerInterest]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'listDonationPledges' : ActorMethod<[], Array<DonationPledge>>,
  'listVolunteerInterests' : ActorMethod<[], Array<VolunteerInterest>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'submitDonationPledge' : ActorMethod<[DonationPledge], undefined>,
  'submitVolunteerInterest' : ActorMethod<[VolunteerInterest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];